server {
    listen 80;
    server_name _;

    root /var/www/html;
    index index.html;

        # 🔴 สำคัญมาก: Service Worker
    location /service-worker.js {
        add_header Cache-Control "no-cache";
        try_files $uri =404;
    }

    # Static assets (cache ยาวได้)
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # SPA fallback
    location / {
        try_files $uri $uri/ /index.html;
    }

    # optional: cache static files
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf)$ {
        expires 7d;
        add_header Cache-Control "public";
        access_log off;
    }
}
